2024-08-16 23:13:37,945 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\svett\PycharmProjects\Module12\tests_12_4.py", line 23, in test_run
    person = Runner(2)
             ^^^^^^^^^
  File "C:\Users\svett\PycharmProjects\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-08-16 23:13:37,948 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\svett\PycharmProjects\Module12\tests_12_4.py", line 12, in test_walk
    person = Runner('name', speed=-5)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svett\PycharmProjects\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
